name: tekartik_list_view_test_app_lib
description: List view test app lib
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  tekartik_app_list_view_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_list_view
    version: '>=0.1.0'
  tekartik_app_dev_menu_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_dev_menu
  tekartik_app_platform:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_platform
    version: '>=0.1.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'

flutter:
  uses-material-design: true
resolution: workspace
