name: tekartik_app_flutter_utils_test_app
description: flutter utils test app
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi_web: '>=0.4.5+1'
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ">=1.0.8"
  tekartik_prefs_test_app_lib:
    path: ../prefs_test_app_lib
  tekartik_idb_test_app_lib:
    path: ../idb_test_app_lib
  tekartik_sqflite_test_app_lib:
    path: ../sqflite_test_app_lib
  tekartik_fs_test_app_lib:
    path: ../fs_test_app_lib
  tekartik_sembast_test_app_lib:
    path: ../sembast_test_app_lib
  tekartik_widget_test_app_lib:
    path: ../widget_test_app_lib
  tekartik_app_plugin_test_app_lib:
    path: ../app_plugin_test_app_lib
  tekartik_common_test_app_lib:
    path: ../common_test_app_lib
  tekartik_common_web_test_app_lib:
    path: ../common_web_test_app_lib
  tekartik_navigator_test_app_lib:
    path: ../navigator_test_app_lib
  tekartik_image_test_app_lib:
    path: ../image_test_app_lib
  tekartik_app_roboto_test_app_lib:
    path: ../roboto_test_app_lib
  tekartik_app_flutter_common_web_utils:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_common_web
    version: '>=0.1.0'
  tekartik_test_menu_flutter:
    git:
      url: https://github.com/tekartik/test_menu_flutter
      ref: dart3a
      path: test_menu_flutter
    version: '>=0.2.3'
  tekartik_app_roboto:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_roboto
  tekartik_app_flutter_sqflite:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_sqflite
dev_dependencies:
  flutter_test:
    sdk: flutter
  dev_build: ">=1.1.2"
  path: ">=1.9.0"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      ref: dart3a
      path: packages/lints_flutter
    version: '>=0.1.0'
  process_run: ">=1.2.1+1"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: packages/tekartik_app_roboto/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: RobotoMono
      fonts:
        - asset: packages/tekartik_app_roboto/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: packages/tekartik_app_roboto/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        # missing
        # - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Thin.ttf
        #  weight: 100
        - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
          weight: 400
        # missing
        # - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Medium.ttf
        #  weight: 500
        - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Bold.ttf
          weight: 700
        # - asset: packages/tekartik_app_roboto/fonts/RobotoCondensed/RobotoCondensed-Black.ttf
        #  weight: 900
resolution: workspace

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
