name: tekartik_app_list_view_flutter
description: ListView for Flutter with lazy loading of items by offset/limit and count, Future or Stream based, with CustomScrollView/ListView.custom support.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter

resolution: workspace
